name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  solutionFile: ProjectedFSLib.Managed.sln
  configuration: Release
  baseVersion: 1.0.0

permissions:
  contents: read
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Version
      run: |
        echo "buildVersion=${{ env.baseVersion }}.${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "nugetVersion=${{ env.baseVersion }}-ci${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          6.x

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: NuGet Restore
      working-directory: ${{ github.workspace }}
      run: dotnet restore ${{ env.solutionFile }}

    - name: Build
      working-directory: ${{ github.workspace }}
      run: msbuild /p:Configuration=${{ env.configuration }} /p:Version=${{ env.buildVersion }} ${{ env.solutionFile }}

    - name: Pack
      working-directory: ${{github.workspace}}/ProjFSSharp
      run: dotnet pack ProjFSSharp.csproj -c ${{ env.configuration }} -p:PackageVersion=${{ env.nugetVersion }} --no-build --output ${{ github.workspace }}/NuGetPreview

    - name: Upload Artifacts
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v3
      with:
        name: NuGetPreview
        path: ${{ github.workspace }}/NuGetPreview/*nupkg
        if-no-files-found: error